### ISSUE TITLE
Add support for export using IPFIX / Netflow

### ISSUE THREAD

**Issue by eranra** [netobserv/netobserv-ebpf-agent#26]
This will remove the strong bond between the agent and FLP which is currently using a non-standard and proprietary gRPC protocol and allows the agent the be used by other tools that work with standard IPFIX / Netflow. For an upstream project, this is needed if we are looking for external contributions.

**Comment by eranra** [comment]
ref: https://github.com/netobserv/netobserv-ebpf-agent/blob/main/pkg/exporter/grpc_proto.go

**Comment by praveingk** [comment]
This is now addressed in https://github.com/netobserv/netobserv-ebpf-agent/pull/64
