### ISSUE TITLE
Add feature to exclude ip from flow

### ISSUE THREAD

**Issue by hihellobolke** [netobserv/netobserv-ebpf-agent#266]
As a user of this agent, it can overwhelm the flow pipeline (for k8s enriching) on very large clusters. It would be optimal, if I could add ip filtering in the netobserv-ebpf-agent so that I can pass only interesting flow to downstream flow pipline.

As a very hacky example https://github.com/netobserv/netobserv-ebpf-agent/commit/c55b0acbb0238b2f21beba022381ea87b9014f31

**Comment by msherif1234** [comment]
Hi @hihellobolke thanks for reaching out we have plans to filter at the low level in ebpf per direction so only matching flows will be stored in our tables will that work for your usecase ?

**Comment by hihellobolke** [comment]
Yes @msherif1234 that will work well!
