### ISSUE TITLE
Is there anything stopping the ebpf agent from running outside of k8s?

### ISSUE THREAD

**Issue by ewollesen** [netobserv/netobserv-ebpf-agent#284]
I've been reading through the docs here and I'm wondering if the ebpf agent can be deployed without k8s? 

I have a small edge router that I'd like to gather IPFIX data from. Is there any architectural reason I couldn't compile and run the agent locally, without k8s or the the k8s operator? Would this be an uphill battle at every step? Any gotchas to look out for?

PS- Apologies if there's a better place to ask this kind of question. I didn't see any information about an IRC channel / discord / mailing list, etc.

**Comment by jotak** [comment]
(please let us know if you find issues while building)

**Comment by ewollesen** [comment]
Thanks @jotak !

Thanks for confirming, and for the systemd example, that will be useful.

I was able to build it no problem, but I haven't had any time to get much further yet. It seems to run, but I don't have a collector connected up to it yet to really know.

**Comment by jotak** [comment]
@ewollesen if you don't want to write your own collector you may use our [flowlogs-pipeline](https://github.com/netobserv/flowlogs-pipeline) and even start the agent with the "direct-FLP" mode (it's the same as running the agent + flowlogs-pipeline, except that flowlogs-pipeline doesn't run as a separate process but is directly run within the agent process)
flowlogs-pipeline can be useful as it has more exporting options, allows to define custom filtering/mapping rules, allows to generate prometheus or opentelemtry metrics out of flow logs, etc.

For a simple quick start with this, you can run: 

```bash
export EXPORT="direct-flp"
export FLP_CONFIG='{"pipeline":[{"name": "writer","follows": "preset-ingester"}],"parameters":[{"name": "writer","write": {"type": "stdout","stdout": {"format":"json"}}}]}'
sudo -E bin/netobserv-ebpf-agent 
```

Your terminal should output logs like that:

```
{"AgentIP":"192.168.1.18","Bytes":568,"DnsErrno":0,"Dscp":0,"DstAddr":"192.168.1.18","DstMac":"...","DstPort":40596,"Duplicate":false,"Etype":2048,"Flags":16,"FlowDirection":0,"Interface":"enp0s20f0u2u1u2","Packets":1,"Proto":6,"SrcAddr":"...","SrcMac":"...","SrcPort":443,"TimeFlowEndMs":1709539879400,"TimeFlowStartMs":1709539879400,"TimeReceived":1709539884}
{"AgentIP":"192.168.1.18","Bytes":113,"DnsErrno":0,"Dscp":0,"DstAddr":"...","DstMac":"...","DstPort":51412,"Duplicate":false,"Etype":34525,"Flags":16,"FlowDirection":0,"Interface":"enp0s20f0u2u1u2","Packets":1,"Proto":6,"SrcAddr":"...","SrcMac":"...","SrcPort":443,"TimeFlowEndMs":1709539880887,"TimeFlowStartMs":1709539880887,"TimeReceived":1709539884}
etc.
```

**Comment by ewollesen** [comment]
@jotak thanks the additional resources, I appreciate it.

I have a collector that I've written myself now. It's up and running, and working well.

I'm curious to have a look through the flowlogs-pipeline code though, to see how it does a few things, I bet I can learn a trick or two.

Thanks again. :)
