### ISSUE TITLE
Questions about Flow collections

### ISSUE THREAD

**Issue by ScmTble** [netobserv/netobserv-ebpf-agent#330]
Hello, I noticed the content about Flow collections [docs](https://github.com/netobserv/netobserv-ebpf-agent/blob/main/docs/ebpf_implementation.md#flow-collisions) in docs, but I couldn't find the relevant code in [tracer. go](https://github.com/netobserv/netobserv-ebpf-agent/blob/main/pkg/ebpf/tracer.go). Did I miss anything? thanks

**Comment by msherif1234** [comment]
Hi @ScmTble not sure I understand the question or the exact code u are looking for
but if u are referring to the code the read the hash tables in userspace
https://github.com/netobserv/netobserv-ebpf-agent/blob/main/pkg/ebpf/tracer.go#L497
which is triggered from the eviction logic here
https://github.com/netobserv/netobserv-ebpf-agent/blob/main/pkg/flow/tracer_map.go#L104

pls let me know if the above isn't what u are looking for

Thanks!!

**Comment by ScmTble** [comment]
> Hi @ScmTble not sure I understand the question or the exact code u are looking for but if u are referring to the code the read the hash tables in userspace [`main`/pkg/ebpf/tracer.go#L497](https://github.com/netobserv/netobserv-ebpf-agent/blob/main/pkg/ebpf/tracer.go?rgh-link-date=2024-05-06T10%3A48%3A07Z#L497) which is triggered from the eviction logic here [`main`/pkg/flow/tracer_map.go#L104](https://github.com/netobserv/netobserv-ebpf-agent/blob/main/pkg/flow/tracer_map.go?rgh-link-date=2024-05-06T10%3A48%3A07Z#L104)
> 
> pls let me know if the above isn't what u are looking for
> 
> Thanks!!

Yes, thank you for your answer. I am a beginner in ebpf and have learned a lot from this project
