### ISSUE TITLE
direction configuration

### ISSUE THREAD

**Issue by joewilliams** [netobserv/netobserv-ebpf-agent#57]
Hello! Thanks for this project I have been testing it and it seems great. 

Is there any interest in a PR that would add a configuration option to only monitor flows in a specific direction? For instance I only care about ingress flows, coming from outside the node where the agent is running rather than egress flows originating from the node itself. It looks like the [code](https://github.com/netobserv/netobserv-ebpf-agent/blob/main/bpf/flows.c#L172) already tracks flow direction so I believe this could be a configuration option to track ingress, egress or both.

Let me know what you think.

**Comment by joewilliams** [comment]
I guess it could be easily turned on or off from [here](https://github.com/netobserv/netobserv-ebpf-agent/blob/c696bb0b7e4243845fe5289ac4a07727df517401/bpf/flows.c#L216-L224)?

**Comment by jotak** [comment]
It sounds like an interesting setting to add, @mariomac , thoughts?

**Comment by mariomac** [comment]
Done: https://github.com/netobserv/netobserv-ebpf-agent/pull/58

**Comment by joewilliams** [comment]
Awesome, I was happy to submit a PR myself, thanks for implementing it!
